In [1]:
import numpy as np

In [2]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [10]:
f = np.full((2,3),5)
print(np.shape(f))
f

(2, 3)


array([[5, 5, 5],
       [5, 5, 5]])

In [6]:
np.zeros(4).T

array([0., 0., 0., 0.])

In [29]:
#가우스-조던 소거법 적용 (해가 있는 경우)

#A 출력 함수
def pprint(msg, A):
  print("---",msg,"---")
  (n,m) = np.shape(A)
  for i in range(0,n):
    line = ""
    for j in range(0,m):
      line += "{0:.2f}".format(A[i,j]) + "\t"
      if j == n-1:
        line += "|"
    print(line)
  print("")

#가우스 조던 소거법 수행 함수
def gauss(A):
  (n,m) = np.shape(A)

  for i in range(0,n):
    max_elmt = abs(A[i,i])
    max_row = i
    for k in range(i+1,n):
      if abs(A[k,i]) > max_elmt:
        max_elmt = abs(A[k,i])
        max_row = k
    
    for k in range(i,m):
      tmp = A[max_row, k]
      A[max_row,k] = A[i,k]
      A[i,k] = tmp
    
    piv = A[i,i]
    for k in range(i,m):
      A[i,k] = A[i,k]/piv

    for k in range(0,n):
      if k != i:
        c = A[k,i]/A[i,i]
        for j in range(i,m):
          if i == j:
            A[k,j] = 0
          else:
            A[k,j] = A[k,j] - c * A[i,j]
    pprint(str(i+1) + "번째 반복", A) #중간과정 출력

  X = np.zeros(n)
  for i in range(0,n):
    X[i] = A[i,n]
  return X  


In [30]:
A = np.array([[2,2,4,18],[1,3,2,13],[3,1,3,14]])
pprint("A 행렬",A)

--- A 행렬 ---
2.00	2.00	4.00	|18.00	
1.00	3.00	2.00	|13.00	
3.00	1.00	3.00	|14.00	



In [31]:
X = gauss(A)

--- 1번째 반복 ---
1.00	0.00	1.00	|4.00	
0.00	3.00	1.00	|9.00	
0.00	2.00	2.00	|10.00	

--- 2번째 반복 ---
1.00	0.00	1.00	|4.00	
0.00	1.00	0.00	|3.00	
0.00	0.00	2.00	|4.00	

--- 3번째 반복 ---
1.00	0.00	0.00	|2.00	
0.00	1.00	0.00	|3.00	
0.00	0.00	1.00	|2.00	



In [32]:
(n,m) = A.shape
line = "해:\t"
for i in range(0,n):
  line += "{0:.2f}".format(X[i]) + "\t"
print(line)

해:	2.00	3.00	2.00	
